[project]
name = "transcribe"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai",
    "google-api-python-client>=2.184.0",
    "google-auth>=2.41.1",
    "google-auth-oauthlib>=1.2.2",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.5",
    "send2trash>=2.1.0",
    "typer>=0.19.2",
]

[project.scripts]
coo = "coo:app"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["coo", "transcribe"]
